return {
    {
        "mason-org/mason.nvim",
        version = "^1.*",
        lazy = false,
        opts = {
            ensure_installed = {
                "bacon",
                "bacon-ls",
                "bash-language-server",
                "clang-format",
                "clangd",
                "cmakelang",
                "cmakelint",
                "codelldb",
                "csharpier",
                "debugpy",
                "docker-compose-language-service",
                "dockerfile-language-server",
                "flake8",
                "hadolint",
                "json-lsp",
                "lua-language-server",
                "neocmakelsp",
                "netcoredbg",
                "omnisharp",
                "prettier",
                "ruff",
                "shellcheck",
                "shfmt",
                "stylua",
            },
        },
    },
}
